"""The object-storage boundary (Phase 02-2; ADR-0021 §8, ARCHITECTURE §7).

* Keys are generated by the application (``tenants/<tenant>/files/<id>``) and
  never come from a client. The bucket is private; nothing here produces a
  public or presigned URL.
* Errors never carry the key, bucket, endpoint or credentials: callers turn
  :class:`StorageError` into a 503 and log only its type.
"""

from typing import Protocol


class StorageError(Exception):
    """The object store failed or is unreachable. The message is generic."""


class ObjectNotFoundError(StorageError):
    """The object does not exist (metadata without content: an operational fault)."""


class ObjectStorage(Protocol):
    async def put(self, key: str, data: bytes, *, content_type: str) -> None:
        """Store ``data`` under ``key`` (private, overwriting nothing the caller did not create)."""
        ...

    async def get(self, key: str) -> bytes:
        """The object's bytes; :class:`ObjectNotFoundError` when it does not exist."""
        ...

    async def delete(self, key: str) -> None:
        """Remove the object (best-effort cleanup only; documents are never deleted)."""
        ...
