"""Pure admissions rules (Phase 02-2; ADR-0021 §3-§8): transitions, numbering and uploads.

The upload pipeline is tested with generated bytes only: tiny PDFs (plain,
with active content, with ``#xx``-escaped names, with a compressed object
stream, encrypted), PNG and JPEG signatures, and hostile file names.
"""

import itertools
import zlib
from datetime import date

import pytest

from app.modules.applications.domain import (
    REVIEW_TRANSITIONS,
    ApplicationStatus,
    ReviewProblem,
    clean_cdc,
    clean_indos,
    clean_postal_code,
    missing_for_submit,
    review_problem,
)
from app.modules.documents.domain import VERIFICATION, DocumentStatus
from app.modules.documents.validation import (
    FILE_NAME_MAX_LENGTH,
    MAX_FILE_BYTES,
    UploadProblem,
    UploadRejectedError,
    detect_type,
    pdf_problem,
    sanitize_file_name,
    validate_upload,
)
from app.modules.leads.domain import ActivityKind as LeadActivityKind
from app.modules.students.domain import SequenceName, format_number

S = ApplicationStatus


# --- Application lifecycle -----------------------------------------------------------------


def test_review_moves_pair_by_pair() -> None:
    decisions = {S.APPROVED, S.CORRECTION_REQUIRED, S.REJECTED, S.NOT_ELIGIBLE}
    expected = {
        S.SUBMITTED: decisions | {S.UNDER_REVIEW},
        S.UNDER_REVIEW: decisions,
    }
    for source, target in itertools.product(ApplicationStatus, repeat=2):
        allowed = target in expected.get(source, set())
        assert REVIEW_TRANSITIONS.allows(source, target) is allowed, (source, target)
    # Reviewers never set ADMITTED, the reserved statuses, or go back to a draft.
    reachable = {t for s in ApplicationStatus for t in REVIEW_TRANSITIONS.targets(s)}
    assert not reachable & {S.ADMITTED, S.DRAFT, S.DOCUMENT_VERIFICATION, S.ELIGIBLE}


def test_review_problems() -> None:
    assert review_problem(S.DRAFT, S.APPROVED, reason=None, unverified_documents=0) is (
        ReviewProblem.INVALID
    )
    for target in (S.CORRECTION_REQUIRED, S.REJECTED, S.NOT_ELIGIBLE):
        assert review_problem(S.SUBMITTED, target, reason=None, unverified_documents=0) is (
            ReviewProblem.REASON_REQUIRED
        )
        assert review_problem(S.SUBMITTED, target, reason="x", unverified_documents=3) is None
    assert review_problem(S.UNDER_REVIEW, S.APPROVED, reason=None, unverified_documents=1) is (
        ReviewProblem.DOCUMENTS_PENDING
    )
    # No checklist (Y4): an application without pending documents may be approved.
    assert review_problem(S.UNDER_REVIEW, S.APPROVED, reason=None, unverified_documents=0) is None
    assert review_problem(S.SUBMITTED, S.UNDER_REVIEW, reason=None, unverified_documents=2) is None


def test_submission_needs_the_core_details_a_contact_and_the_declaration() -> None:
    complete = {
        "full_name": "Arjun Nair",
        "date_of_birth": date(2006, 3, 1),
        "highest_qualification": "12th PCM",
        "email": "arjun@example.com",
    }
    assert missing_for_submit(complete, declared=True) == []
    assert missing_for_submit(complete, declared=False) == ["declaration"]
    assert missing_for_submit({**complete, "email": None}, declared=True) == ["contact"]
    assert missing_for_submit({}, declared=False) == [
        "full_name",
        "date_of_birth",
        "highest_qualification",
        "contact",
        "declaration",
    ]


def test_maritime_identifiers_and_postal_codes() -> None:
    assert clean_indos(" 15zl 1234 ") == "15ZL1234"
    assert clean_indos("") is None
    assert clean_cdc("mum 123456") == "MUM123456"
    assert clean_cdc("MUM/2020/1234") == "MUM/2020/1234"
    assert clean_postal_code(" 400  001 ") == "400 001"
    for bad in ("12", "<script>", "15ZL-1234", "x" * 17):
        with pytest.raises(ValueError, match="malformed"):
            clean_indos(bad)
    with pytest.raises(ValueError, match="malformed"):
        clean_cdc("../etc")
    with pytest.raises(ValueError, match="malformed"):
        clean_postal_code("40;0")


def test_the_lead_gains_only_the_application_started_activity() -> None:
    assert LeadActivityKind.APPLICATION_STARTED.value == "APPLICATION_STARTED"


# --- Documents and numbering ---------------------------------------------------------------


def test_only_a_document_under_review_is_decided() -> None:
    for source, target in itertools.product(DocumentStatus, repeat=2):
        allowed = source is DocumentStatus.UNDER_REVIEW and target in {
            DocumentStatus.VERIFIED,
            DocumentStatus.REJECTED,
        }
        assert VERIFICATION.allows(source, target) is allowed, (source, target)


def test_numbers_are_prefixed_per_year_and_widen() -> None:
    assert format_number(SequenceName.APPLICATION, 2026, 1) == "APP-2026-00001"
    assert format_number(SequenceName.ADMISSION, 2026, 42) == "ADM-2026-00042"
    assert format_number(SequenceName.STUDENT, 2027, 123456) == "STU-2027-123456"
    for year, value in ((2026, 0), (1999, 1), (10000, 1)):
        with pytest.raises(ValueError, match="out of range"):
            format_number(SequenceName.STUDENT, year, value)


# --- Upload validation ---------------------------------------------------------------------

PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 32
JPEG = b"\xff\xd8\xff\xe0" + b"\x00" * 32


def pdf(*objects: bytes) -> bytes:
    body = b"\n".join(objects)
    return b"%PDF-1.7\n" + body + b"\ntrailer\n<< /Root 1 0 R >>\n%%EOF\n"


PLAIN_PDF = pdf(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj")


def object_stream(payload: bytes) -> bytes:
    compressed = zlib.compress(payload)
    return (
        b"5 0 obj\n<< /Type /ObjStm /N 1 /First 4 /Filter /FlateDecode /Length "
        + str(len(compressed)).encode()
        + b" >>\nstream\n"
        + compressed
        + b"\nendstream\nendobj"
    )


def test_sanitized_file_names_are_display_only() -> None:
    assert sanitize_file_name("Passport scan.PDF") == "Passport scan.pdf"
    assert sanitize_file_name("C:\\Users\\arjun\\cdc.jpg") == "cdc.jpg"
    assert sanitize_file_name("../../etc/marks.png") == "marks.png"
    assert sanitize_file_name("..") is None
    assert sanitize_file_name(".pdf") is None
    assert sanitize_file_name("noextension") is None
    assert sanitize_file_name("re\u0000port\u202e.pdf") == "report.pdf"
    assert sanitize_file_name('a<b>"c|d.pdf') == "a_b__c_d.pdf"
    long = sanitize_file_name("x" * 500 + ".pdf")
    assert long is not None
    assert len(long) == FILE_NAME_MAX_LENGTH
    assert long.endswith(".pdf")


def test_detected_types() -> None:
    assert detect_type(PLAIN_PDF) == "application/pdf"
    assert detect_type(PNG) == "image/png"
    assert detect_type(JPEG) == "image/jpeg"
    assert detect_type(b"<html>") is None
    assert detect_type(b"MZ\x90\x00") is None


def test_valid_files_pass_with_their_checksum() -> None:
    result = validate_upload("passport.pdf", "application/pdf", PLAIN_PDF)
    assert result.content_type == "application/pdf"
    assert result.size == len(PLAIN_PDF)
    assert len(result.sha256) == 64
    assert validate_upload("photo.JPEG", "image/jpeg", JPEG).file_name == "photo.jpeg"
    assert validate_upload("marks.png", "image/png; charset=binary", PNG).content_type == (
        "image/png"
    )


@pytest.mark.parametrize(
    ("name", "declared", "data", "problem"),
    [
        ("a.pdf", "application/pdf", b"", UploadProblem.EMPTY),
        ("a.pdf", "application/pdf", b"%PDF-" + b"0" * MAX_FILE_BYTES, UploadProblem.TOO_LARGE),
        (None, "application/pdf", PLAIN_PDF, UploadProblem.NAME),
        ("a.exe", "application/pdf", PLAIN_PDF, UploadProblem.TYPE),
        ("a.html", "text/html", b"<html>", UploadProblem.TYPE),
        ("a.svg", "image/svg+xml", b"<svg/>", UploadProblem.TYPE),
        ("a.pdf", "application/octet-stream", PLAIN_PDF, UploadProblem.TYPE),
        ("a.pdf", "application/pdf", PNG, UploadProblem.MISMATCH),
        ("a.png", "image/png", JPEG, UploadProblem.MISMATCH),
        ("a.png", "application/pdf", PLAIN_PDF, UploadProblem.MISMATCH),
        ("a.pdf", "application/pdf", b"MZ\x90\x00 not a pdf", UploadProblem.MISMATCH),
        ("a.pdf.exe", "application/pdf", PLAIN_PDF, UploadProblem.TYPE),
    ],
    ids=lambda value: value if isinstance(value, str) and len(value) < 40 else "data",
)
def test_rejected_uploads(
    name: str | None, declared: str, data: bytes, problem: UploadProblem
) -> None:
    with pytest.raises(UploadRejectedError) as raised:
        validate_upload(name, declared, data)
    assert raised.value.problem is problem


@pytest.mark.parametrize(
    "payload",
    [
        b"<< /OpenAction << /S /JavaScript /JS (app.alert(1)) >> >>",
        b"<< /S /Launch /F (cmd.exe) >>",
        b"<< /Names << /EmbeddedFiles 9 0 R >> >>",
        b"<< /AcroForm << /XFA 7 0 R >> >>",
        b"<< /S /SubmitForm /F (https://example.com) >>",
        b"<< /S /J#61vaScript /J#53 (x) >>",
        b"<< /RichMedia 3 0 R >>",
    ],
    ids=["javascript", "launch", "embedded", "xfa", "submit", "escaped", "richmedia"],
)
def test_pdfs_with_active_content_are_refused(payload: bytes) -> None:
    data = pdf(b"1 0 obj\n" + payload + b"\nendobj")
    assert pdf_problem(data) is UploadProblem.PDF_ACTIVE
    with pytest.raises(UploadRejectedError) as raised:
        validate_upload("form.pdf", "application/pdf", data)
    assert raised.value.problem is UploadProblem.PDF_ACTIVE


def test_active_content_hidden_in_a_compressed_object_stream_is_found() -> None:
    hidden = pdf(object_stream(b"6 0 << /S /JavaScript /JS (x) >>"))
    assert b"JavaScript" not in hidden  # only visible after decompression
    assert pdf_problem(hidden) is UploadProblem.PDF_ACTIVE
    clean = pdf(object_stream(b"6 0 << /Type /Page /Parent 2 0 R >>"))
    assert pdf_problem(clean) is None
    escaped = pdf(
        b"5 0 obj\n<< /Type /Obj#53tm /Length 3 >>\nstream\n"
        + zlib.compress(b"<< /Launch 1 >>")
        + b"\nendstream\nendobj"
    )
    assert pdf_problem(escaped) is UploadProblem.PDF_ACTIVE


def test_unreadable_or_bomb_object_streams_and_encrypted_pdfs_are_refused() -> None:
    broken = pdf(b"5 0 obj\n<< /Type /ObjStm >>\nstream\nnot-zlib\nendstream\nendobj")
    assert pdf_problem(broken) is UploadProblem.PDF_UNREADABLE
    bomb = pdf(object_stream(b"0" * (17 * 1024 * 1024)))
    assert pdf_problem(bomb) is UploadProblem.PDF_UNREADABLE
    encrypted = PLAIN_PDF.replace(b"<< /Root 1 0 R >>", b"<< /Root 1 0 R /Encrypt 9 0 R >>")
    assert pdf_problem(encrypted) is UploadProblem.PDF_ENCRYPTED
    # Large image or page streams are not decompressed (no ObjStm): no budget to exhaust.
    image = pdf(
        b"7 0 obj\n<< /Subtype /Image >>\nstream\n" + b"\x00" * 1000 + b"\nendstream\nendobj"
    )
    assert pdf_problem(image) is None
