"""Pure admissions rules (Phase 02-2; ADR-0021 §3-§8): transitions, numbering and uploads.

The upload pipeline is tested with generated bytes only: tiny PDFs (plain,
with active content, with ``#xx``-escaped names, with a compressed object
stream, encrypted), PNG and JPEG signatures, and hostile file names.
"""

import itertools
import tracemalloc
import zlib
from collections import Counter
from datetime import date

import pytest

from app.modules.applications.domain import (
    REVIEW_TRANSITIONS,
    ApplicationStatus,
    ReviewProblem,
    clean_cdc,
    clean_indos,
    clean_postal_code,
    missing_for_submit,
    review_problem,
)
from app.modules.documents import validation
from app.modules.documents.domain import VERIFICATION, DocumentStatus
from app.modules.documents.validation import (
    FILE_NAME_MAX_LENGTH,
    INFLATED_TOTAL_MAX_BYTES,
    MAX_FILE_BYTES,
    OBJECT_STREAM_MAX_BYTES,
    OBJECT_STREAMS_MAX,
    UploadProblem,
    UploadRejectedError,
    detect_type,
    pdf_problem,
    sanitize_file_name,
    validate_upload,
)
from app.modules.leads.domain import ActivityKind as LeadActivityKind
from app.modules.students.domain import SequenceName, format_number

S = ApplicationStatus


# --- Application lifecycle -----------------------------------------------------------------


def test_review_moves_pair_by_pair() -> None:
    decisions = {S.APPROVED, S.CORRECTION_REQUIRED, S.REJECTED, S.NOT_ELIGIBLE}
    expected = {
        S.SUBMITTED: decisions | {S.UNDER_REVIEW},
        S.UNDER_REVIEW: decisions,
    }
    for source, target in itertools.product(ApplicationStatus, repeat=2):
        allowed = target in expected.get(source, set())
        assert REVIEW_TRANSITIONS.allows(source, target) is allowed, (source, target)
    # Reviewers never set ADMITTED, the reserved statuses, or go back to a draft.
    reachable = {t for s in ApplicationStatus for t in REVIEW_TRANSITIONS.targets(s)}
    assert not reachable & {S.ADMITTED, S.DRAFT, S.DOCUMENT_VERIFICATION, S.ELIGIBLE}


def test_review_problems() -> None:
    assert review_problem(S.DRAFT, S.APPROVED, reason=None, unverified_documents=0) is (
        ReviewProblem.INVALID
    )
    for target in (S.CORRECTION_REQUIRED, S.REJECTED, S.NOT_ELIGIBLE):
        assert review_problem(S.SUBMITTED, target, reason=None, unverified_documents=0) is (
            ReviewProblem.REASON_REQUIRED
        )
        assert review_problem(S.SUBMITTED, target, reason="x", unverified_documents=3) is None
    assert review_problem(S.UNDER_REVIEW, S.APPROVED, reason=None, unverified_documents=1) is (
        ReviewProblem.DOCUMENTS_PENDING
    )
    # No checklist (Y4): an application without pending documents may be approved.
    assert review_problem(S.UNDER_REVIEW, S.APPROVED, reason=None, unverified_documents=0) is None
    assert review_problem(S.SUBMITTED, S.UNDER_REVIEW, reason=None, unverified_documents=2) is None


def test_submission_needs_the_core_details_a_contact_and_the_declaration() -> None:
    complete = {
        "full_name": "Arjun Nair",
        "date_of_birth": date(2006, 3, 1),
        "highest_qualification": "12th PCM",
        "email": "arjun@example.com",
    }
    assert missing_for_submit(complete, declared=True) == []
    assert missing_for_submit(complete, declared=False) == ["declaration"]
    assert missing_for_submit({**complete, "email": None}, declared=True) == ["contact"]
    assert missing_for_submit({}, declared=False) == [
        "full_name",
        "date_of_birth",
        "highest_qualification",
        "contact",
        "declaration",
    ]


def test_maritime_identifiers_and_postal_codes() -> None:
    assert clean_indos(" 15zl 1234 ") == "15ZL1234"
    assert clean_indos("") is None
    assert clean_cdc("mum 123456") == "MUM123456"
    assert clean_cdc("MUM/2020/1234") == "MUM/2020/1234"
    assert clean_postal_code(" 400  001 ") == "400 001"
    for bad in ("12", "<script>", "15ZL-1234", "x" * 17):
        with pytest.raises(ValueError, match="malformed"):
            clean_indos(bad)
    with pytest.raises(ValueError, match="malformed"):
        clean_cdc("../etc")
    with pytest.raises(ValueError, match="malformed"):
        clean_postal_code("40;0")


def test_the_lead_gains_only_the_application_started_activity() -> None:
    assert LeadActivityKind.APPLICATION_STARTED.value == "APPLICATION_STARTED"


# --- Documents and numbering ---------------------------------------------------------------


def test_only_a_document_under_review_is_decided() -> None:
    for source, target in itertools.product(DocumentStatus, repeat=2):
        allowed = source is DocumentStatus.UNDER_REVIEW and target in {
            DocumentStatus.VERIFIED,
            DocumentStatus.REJECTED,
        }
        assert VERIFICATION.allows(source, target) is allowed, (source, target)


def test_numbers_are_prefixed_per_year_and_widen() -> None:
    assert format_number(SequenceName.APPLICATION, 2026, 1) == "APP-2026-00001"
    assert format_number(SequenceName.ADMISSION, 2026, 42) == "ADM-2026-00042"
    assert format_number(SequenceName.STUDENT, 2027, 123456) == "STU-2027-123456"
    for year, value in ((2026, 0), (1999, 1), (10000, 1)):
        with pytest.raises(ValueError, match="out of range"):
            format_number(SequenceName.STUDENT, year, value)


# --- Upload validation ---------------------------------------------------------------------

PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 32
JPEG = b"\xff\xd8\xff\xe0" + b"\x00" * 32


def pdf(*objects: bytes) -> bytes:
    body = b"\n".join(objects)
    return b"%PDF-1.7\n" + body + b"\ntrailer\n<< /Root 1 0 R >>\n%%EOF\n"


PLAIN_PDF = pdf(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj")


def object_stream(payload: bytes) -> bytes:
    compressed = zlib.compress(payload)
    return (
        b"5 0 obj\n<< /Type /ObjStm /N 1 /First 4 /Filter /FlateDecode /Length "
        + str(len(compressed)).encode()
        + b" >>\nstream\n"
        + compressed
        + b"\nendstream\nendobj"
    )


def test_sanitized_file_names_are_display_only() -> None:
    assert sanitize_file_name("Passport scan.PDF") == "Passport scan.pdf"
    assert sanitize_file_name("C:\\Users\\arjun\\cdc.jpg") == "cdc.jpg"
    assert sanitize_file_name("../../etc/marks.png") == "marks.png"
    assert sanitize_file_name("..") is None
    assert sanitize_file_name(".pdf") is None
    assert sanitize_file_name("noextension") is None
    assert sanitize_file_name("re\u0000port\u202e.pdf") == "report.pdf"
    assert sanitize_file_name('a<b>"c|d.pdf') == "a_b__c_d.pdf"
    long = sanitize_file_name("x" * 500 + ".pdf")
    assert long is not None
    assert len(long) == FILE_NAME_MAX_LENGTH
    assert long.endswith(".pdf")


def test_detected_types() -> None:
    assert detect_type(PLAIN_PDF) == "application/pdf"
    assert detect_type(PNG) == "image/png"
    assert detect_type(JPEG) == "image/jpeg"
    assert detect_type(b"<html>") is None
    assert detect_type(b"MZ\x90\x00") is None


def test_valid_files_pass_with_their_checksum() -> None:
    result = validate_upload("passport.pdf", "application/pdf", PLAIN_PDF)
    assert result.content_type == "application/pdf"
    assert result.size == len(PLAIN_PDF)
    assert len(result.sha256) == 64
    assert validate_upload("photo.JPEG", "image/jpeg", JPEG).file_name == "photo.jpeg"
    assert validate_upload("marks.png", "image/png; charset=binary", PNG).content_type == (
        "image/png"
    )


@pytest.mark.parametrize(
    ("name", "declared", "data", "problem"),
    [
        ("a.pdf", "application/pdf", b"", UploadProblem.EMPTY),
        ("a.pdf", "application/pdf", b"%PDF-" + b"0" * MAX_FILE_BYTES, UploadProblem.TOO_LARGE),
        (None, "application/pdf", PLAIN_PDF, UploadProblem.NAME),
        ("a.exe", "application/pdf", PLAIN_PDF, UploadProblem.TYPE),
        ("a.html", "text/html", b"<html>", UploadProblem.TYPE),
        ("a.svg", "image/svg+xml", b"<svg/>", UploadProblem.TYPE),
        ("a.pdf", "application/octet-stream", PLAIN_PDF, UploadProblem.TYPE),
        ("a.pdf", "application/pdf", PNG, UploadProblem.MISMATCH),
        ("a.png", "image/png", JPEG, UploadProblem.MISMATCH),
        ("a.png", "application/pdf", PLAIN_PDF, UploadProblem.MISMATCH),
        ("a.pdf", "application/pdf", b"MZ\x90\x00 not a pdf", UploadProblem.MISMATCH),
        ("a.pdf.exe", "application/pdf", PLAIN_PDF, UploadProblem.TYPE),
    ],
    ids=lambda value: value if isinstance(value, str) and len(value) < 40 else "data",
)
def test_rejected_uploads(
    name: str | None, declared: str, data: bytes, problem: UploadProblem
) -> None:
    with pytest.raises(UploadRejectedError) as raised:
        validate_upload(name, declared, data)
    assert raised.value.problem is problem


@pytest.mark.parametrize(
    "payload",
    [
        b"<< /OpenAction << /S /JavaScript /JS (app.alert(1)) >> >>",
        b"<< /S /Launch /F (cmd.exe) >>",
        b"<< /Names << /EmbeddedFiles 9 0 R >> >>",
        b"<< /AcroForm << /XFA 7 0 R >> >>",
        b"<< /S /SubmitForm /F (https://example.com) >>",
        b"<< /S /J#61vaScript /J#53 (x) >>",
        b"<< /RichMedia 3 0 R >>",
    ],
    ids=["javascript", "launch", "embedded", "xfa", "submit", "escaped", "richmedia"],
)
def test_pdfs_with_active_content_are_refused(payload: bytes) -> None:
    data = pdf(b"1 0 obj\n" + payload + b"\nendobj")
    assert pdf_problem(data) is UploadProblem.PDF_ACTIVE
    with pytest.raises(UploadRejectedError) as raised:
        validate_upload("form.pdf", "application/pdf", data)
    assert raised.value.problem is UploadProblem.PDF_ACTIVE


def test_active_content_hidden_in_a_compressed_object_stream_is_found() -> None:
    hidden = pdf(object_stream(b"6 0 << /S /JavaScript /JS (x) >>"))
    assert b"JavaScript" not in hidden  # only visible after decompression
    assert pdf_problem(hidden) is UploadProblem.PDF_ACTIVE
    clean = pdf(object_stream(b"6 0 << /Type /Page /Parent 2 0 R >>"))
    assert pdf_problem(clean) is None
    escaped = pdf(
        b"5 0 obj\n<< /Type /Obj#53tm /Length 3 >>\nstream\n"
        + zlib.compress(b"<< /Launch 1 >>")
        + b"\nendstream\nendobj"
    )
    assert pdf_problem(escaped) is UploadProblem.PDF_ACTIVE


def test_unreadable_or_bomb_object_streams_and_encrypted_pdfs_are_refused() -> None:
    broken = pdf(b"5 0 obj\n<< /Type /ObjStm >>\nstream\nnot-zlib\nendstream\nendobj")
    assert pdf_problem(broken) is UploadProblem.PDF_UNREADABLE
    bomb = pdf(object_stream(b"0" * (17 * 1024 * 1024)))
    assert pdf_problem(bomb) is UploadProblem.PDF_UNREADABLE
    encrypted = PLAIN_PDF.replace(b"<< /Root 1 0 R >>", b"<< /Root 1 0 R /Encrypt 9 0 R >>")
    assert pdf_problem(encrypted) is UploadProblem.PDF_ENCRYPTED
    # Large image or page streams are not decompressed (no ObjStm): no budget to exhaust.
    image = pdf(
        b"7 0 obj\n<< /Subtype /Image >>\nstream\n" + b"\x00" * 1000 + b"\nendstream\nendobj"
    )
    assert pdf_problem(image) is None


# --- Resource bounds (the PDF validation denial-of-service fix) ----------------------------


def _counting_inflate(monkeypatch: pytest.MonkeyPatch) -> list[int]:
    """Record the limit of every decompression the pipeline starts."""
    calls: list[int] = []
    original = validation._inflate

    def counting(raw: bytes, limit: int) -> bytes:
        calls.append(limit)
        return original(raw, limit)

    monkeypatch.setattr(validation, "_inflate", counting)
    return calls


def test_the_total_decompressed_size_of_a_pdf_is_bounded(monkeypatch: pytest.MonkeyPatch) -> None:
    # Each stream is under the per-stream limit; three of them exceed the total.
    each = 12 * 1024 * 1024
    assert each < OBJECT_STREAM_MAX_BYTES
    assert 2 * each <= INFLATED_TOTAL_MAX_BYTES < 3 * each
    stream = object_stream(b"0" * each)
    assert pdf_problem(pdf(stream, stream)) is None
    calls = _counting_inflate(monkeypatch)
    many = pdf(*([stream] * 6))
    assert len(many) < 200 * 1024  # a small file
    assert pdf_problem(many) is UploadProblem.PDF_UNREADABLE
    # The third stream may only use what is left of the total, and nothing after it runs.
    assert calls == [
        OBJECT_STREAM_MAX_BYTES,
        OBJECT_STREAM_MAX_BYTES,
        INFLATED_TOTAL_MAX_BYTES - 2 * each,
    ]
    with pytest.raises(UploadRejectedError) as raised:
        validate_upload("bomb.pdf", "application/pdf", many)
    assert raised.value.problem is UploadProblem.PDF_UNREADABLE


def test_an_exhausted_budget_refuses_the_next_stream_without_inflating_it() -> None:
    with pytest.raises(UploadRejectedError) as raised:
        validation._inflate(zlib.compress(b"<< >>"), 0)  # zlib would read 0 as "unlimited"
    assert raised.value.problem is UploadProblem.PDF_UNREADABLE


def test_the_number_of_object_streams_is_bounded(monkeypatch: pytest.MonkeyPatch) -> None:
    stream = object_stream(b"6 0 << /Type /Page >>")
    assert pdf_problem(pdf(*([stream] * OBJECT_STREAMS_MAX))) is None
    calls = _counting_inflate(monkeypatch)
    flood = pdf(*([stream] * (OBJECT_STREAMS_MAX + 50)))
    assert pdf_problem(flood) is UploadProblem.PDF_UNREADABLE
    assert len(calls) == OBJECT_STREAMS_MAX  # stopped at the first stream over the bound


def test_truncated_or_malformed_object_streams_fail_closed() -> None:
    compressed = zlib.compress(b"6 0 << /Type /Page >>" * 50)
    truncated = pdf(
        b"5 0 obj\n<< /Type /ObjStm >>\nstream\n" + compressed[:-8] + b"\nendstream\nendobj"
    )
    assert pdf_problem(truncated) is UploadProblem.PDF_UNREADABLE
    unterminated = b"%PDF-1.7\n5 0 obj\n<< /Type /ObjStm >>\nstream\n" + compressed[:10]
    assert pdf_problem(unterminated) is UploadProblem.PDF_UNREADABLE
    not_flate = pdf(b"5 0 obj\n<< /Type /ObjStm >>\nstream\n\x00\x01\x02\nendstream\nendobj")
    assert pdf_problem(not_flate) is UploadProblem.PDF_UNREADABLE


def test_the_stream_scan_is_linear_in_the_file_size(monkeypatch: pytest.MonkeyPatch) -> None:
    """Many ``stream`` keywords used to rescan the file from its start for each one."""
    scanned: list[int] = []
    original = validation._names

    def measuring(data: bytes) -> Counter[bytes]:
        scanned.append(len(data))
        return original(data)

    monkeypatch.setattr(validation, "_names", measuring)
    for flood in (
        b"%PDF-1.7\n1 0 obj\n" + b"/a stream\n" * 20_000,
        b"%PDF-1.7\n" + b"1 0 obj /a stream\n" * 20_000,  # object headers between them
    ):
        scanned.clear()
        assert pdf_problem(flood) is None
        # One pass over the file for its names, plus disjoint stream dictionaries.
        assert sum(scanned) <= 2 * len(flood)


def test_object_stream_detection_survives_the_linear_scan() -> None:
    # A decoy "stream" inside the dictionary does not hide the object stream after it.
    decoy = (
        b"5 0 obj\n<< /Length 9 /Note (stream\n) /Type /ObjStm >>\nstream\n"
        + zlib.compress(b"<< /S /Launch >>")
        + b"\nendstream\nendobj"
    )
    assert pdf_problem(pdf(decoy)) is UploadProblem.PDF_ACTIVE
    # Streams after an object stream are still found.
    later = pdf(object_stream(b"6 0 << /Type /Page >>"), object_stream(b"7 0 << /S /JavaScript >>"))
    assert pdf_problem(later) is UploadProblem.PDF_ACTIVE


# --- Object-stream association and the name scan (the active-content bypass fix) -----------

HIDDEN = b"6 0 << /S /JavaScript /JS (app.alert(1)) >>"
HARMLESS = b"6 0 << /Type /Page /Parent 2 0 R >>"


def custom_object_stream(payload: bytes, *, extra: bytes = b"", eol: bytes = b"\n") -> bytes:
    """``object_stream`` with extra dictionary entries and a chosen end of line."""
    compressed = zlib.compress(payload)
    return (
        b"5 0 obj\n<< /Type /ObjStm /N 1 /First 4 /Filter /FlateDecode "
        + extra
        + b" /Length "
        + str(len(compressed)).encode()
        + b" >>\nstream"
        + eol
        + compressed
        + b"\nendstream\nendobj"
    )


@pytest.mark.parametrize(
    "extra",
    [b"/Note (obj)", b"/objx 1", b"/Note (endobj) /Tag /obj"],
    ids=["string-obj", "name-objx", "endobj-and-name-obj"],
)
def test_text_like_obj_does_not_hide_an_object_stream(extra: bytes) -> None:
    # Valid PDF syntax: a dictionary may hold any extra entry. These used to be taken for
    # the object boundary, so the stream was never decompressed and the script passed.
    assert b"JavaScript" not in pdf(custom_object_stream(HIDDEN, extra=extra))
    assert pdf_problem(pdf(custom_object_stream(HIDDEN, extra=extra))) is UploadProblem.PDF_ACTIVE
    assert pdf_problem(pdf(custom_object_stream(HARMLESS, extra=extra))) is None


@pytest.mark.parametrize(
    "eol",
    [b"\n", b"\r\n", b"\r", b" \n", b"\t\r\n"],
    ids=["lf", "crlf", "cr-only", "space-lf", "tab-crlf"],
)
def test_every_accepted_line_end_after_stream_is_inspected(eol: bytes) -> None:
    # LF and CRLF are the conforming ends (ISO 32000-2 §7.3.8.1). CR alone and white space
    # before the end of line are not valid syntax, but lenient readers accept them, so the
    # stream is inspected rather than skipped. They used to be skipped (a bypass).
    assert pdf_problem(pdf(custom_object_stream(HIDDEN, eol=eol))) is UploadProblem.PDF_ACTIVE
    assert pdf_problem(pdf(custom_object_stream(HARMLESS, eol=eol))) is None


@pytest.mark.parametrize(
    "data",
    [
        # Not a stream keyword token: the declaration is left without an inspected stream.
        pdf(custom_object_stream(HIDDEN, eol=b"x")),
        # A stream keyword token without a line end.
        pdf(custom_object_stream(HIDDEN, eol=b"%")),
        # A declaration in a string.
        PLAIN_PDF.replace(b"/Type /Catalog", b"/Type /Catalog /Note (/ObjStm)"),
        # A declaration on an object without a stream.
        pdf(b"7 0 obj\n<< /Type /ObjStm /N 0 /First 0 >>\nendobj"),
        # An object header inside a string, after the declaration: misleads the association.
        pdf(custom_object_stream(HIDDEN, extra=b"/Note (1 0 obj)")),
        # A declaration inside an object stream (object streams do not nest).
        pdf(object_stream(b"6 0 << /Type /ObjStm >>")),
        # One inspected object stream and one hidden after a misleading header.
        pdf(object_stream(HARMLESS), custom_object_stream(HIDDEN, extra=b"/Note (9 0 obj)")),
    ],
    ids=[
        "no-keyword",
        "no-line-end",
        "in-a-string",
        "no-stream",
        "header-in-string",
        "nested",
        "second-hidden",
    ],
)
def test_object_stream_declarations_without_an_inspected_stream_fail_closed(
    data: bytes,
) -> None:
    assert pdf_problem(data) is UploadProblem.PDF_UNREADABLE
    with pytest.raises(UploadRejectedError) as raised:
        validate_upload("odd.pdf", "application/pdf", data)
    assert raised.value.problem is UploadProblem.PDF_UNREADABLE


def test_ordinary_pdfs_still_pass() -> None:
    assert pdf_problem(PLAIN_PDF) is None
    # Several object streams, an escaped declaration, and an image stream.
    image = (
        b"7 0 obj\n<< /Subtype /Image /Length 4 >>\nstream\r\n\x00\x01\x02\x03\nendstream\nendobj"
    )
    escaped = custom_object_stream(HARMLESS).replace(b"/ObjStm", b"/Obj#53tm")
    many = pdf(object_stream(HARMLESS), custom_object_stream(HARMLESS, eol=b"\r\n"), escaped, image)
    assert pdf_problem(many) is None
    assert validate_upload("marks.pdf", "application/pdf", many).content_type == "application/pdf"
    # Ten-digit object numbers and other white space in a header.
    spaced = custom_object_stream(HARMLESS).replace(b"5 0 obj", b"1234567890\r\n0\x00obj")
    assert pdf_problem(pdf(spaced)) is None


def test_the_name_scan_keeps_counts_of_watched_names_only() -> None:
    data = (
        b"/Type /Catalog /JavaScript /JS /J#53 /JavaScriptX /J#61vaScript /Obj#53tm /ObjStm "
        b"/Encrypt /abc " * 3
    )
    names = validation._names(data)
    assert set(names) <= validation.WATCHED_NAMES
    assert names == Counter({b"JavaScript": 6, b"JS": 6, b"ObjStm": 6, b"Encrypt": 3})
    # Names after a stream keyword (raw stream content) are still seen.
    raw = pdf(b"7 0 obj\n<< /Length 30 >>\nstream\n<< /S /Launch /F (x) >>\nendstream\nendobj")
    assert pdf_problem(raw) is UploadProblem.PDF_ACTIVE


@pytest.mark.parametrize("name", [b"/ab", b"/a#41", b"/JS"], ids=["plain", "escaped", "watched"])
def test_the_name_scan_does_not_retain_the_names_of_the_file(name: bytes) -> None:
    """Memory is measured by allocation tracing, not time: the earlier scan held every
    name of the file at once (about 15 times the file size for short names)."""
    data = name * (2 * 1024 * 1024 // len(name))
    tracemalloc.start()
    try:
        validation._names(data)
        _, peak = tracemalloc.get_traced_memory()
    finally:
        tracemalloc.stop()
    assert peak < 64 * 1024
