// MTI 360 icon set (T00-07, decision D3; DESIGN-SYSTEM.md §36): one coherent
// family — Lucide — re-exported under stable names. This is the ONLY module that
// may import "lucide-react" (enforced by tokens/guard.test.ts), so the family can
// be swapped or extended in one place. Add icons here when a component needs
// them; keep maritime references subtle (Compass, Anchor).
//
// Lucide icons render aria-hidden="true" unless given an accessible label.
// Decorative icons must stay hidden; meaning is always carried by text.

export type {
  LucideIcon as IconComponent,
  LucideProps as IconProps,
} from "lucide-react";

export {
  Activity as HealthIcon,
  Anchor as AnchorIcon,
  ArrowDown as SortDescendingIcon,
  ArrowDownRight as TrendDownIcon,
  ArrowLeft as BackIcon,
  ArrowRight as ForwardIcon,
  ArrowUp as SortAscendingIcon,
  ArrowUpDown as SortableIcon,
  ArrowUpRight as TrendUpIcon,
  Award as CertificateIcon,
  Bell as NotificationIcon,
  BookOpen as CourseIcon,
  BriefcaseBusiness as PlacementIcon,
  Building2 as InstituteIcon,
  Calendar as CalendarIcon,
  CalendarCheck as AttendanceIcon,
  CalendarDays as ScheduleIcon,
  ChartColumn as AnalyticsIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsLeft as FirstPageIcon,
  ChevronsRight as LastPageIcon,
  CircleAlert as ErrorIcon,
  CircleCheck as SuccessIcon,
  CircleDot as TimelineDotIcon,
  CircleHelp as HelpIcon,
  ClipboardCheck as ExamIcon,
  Clock as ClockIcon,
  Compass as CompassIcon,
  Copy as CopyIcon,
  Download as DownloadIcon,
  Ellipsis as MoreIcon,
  Eye as ViewIcon,
  FileText as FileIcon,
  Globe as WebsiteIcon,
  GraduationCap as AcademicsIcon,
  House as HomeIcon,
  Inbox as EmptyIcon,
  Info as InfoIcon,
  LayoutDashboard as DashboardIcon,
  LifeBuoy as SupportIcon,
  LoaderCircle as SpinnerIcon,
  LockKeyhole as LockIcon,
  LogOut as SignOutIcon,
  Megaphone as MarketingIcon,
  Menu as MenuIcon,
  MessagesSquare as MessageIcon,
  Minus as IndeterminateIcon,
  Minus as TrendFlatIcon,
  PanelLeftClose as CollapseSidebarIcon,
  PanelLeftOpen as ExpandSidebarIcon,
  Pencil as EditIcon,
  Plug as IntegrationIcon,
  Plus as AddIcon,
  Receipt as FeeIcon,
  RotateCw as RetryIcon,
  ScrollText as AuditIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Settings2 as PreferencesIcon,
  ShieldCheck as ComplianceIcon,
  SlidersHorizontal as FilterIcon,
  Sparkles as AiIcon,
  Trash2 as DeleteIcon,
  TriangleAlert as WarningIcon,
  Upload as UploadIcon,
  UserPlus as AdmissionsIcon,
  UserRound as ProfileIcon,
  Users as UsersIcon,
  Wallet as FinanceIcon,
  Workflow as WorkflowIcon,
  X as CloseIcon,
} from "lucide-react";
