"""Shared Phase 02-2 test helpers: applications, documents, admission and students.

Builds on ``courses_leads_support`` (the admissions team: ``maya`` all-campus
manager, ``kiran`` campus A1 manager, ``ravi`` A1 counsellor, ``sita`` A2
counsellor; ``carol`` owns institute B). The application's object storage is
replaced by :class:`InMemoryObjectStorage`; files are generated bytes only.
"""

import uuid
from typing import Any

from courses_leads_support import fake_mobile, new_course
from identity_support import Harness
from tenant_admin_support import data, send

from app.integrations.storage import InMemoryObjectStorage

APPLICATIONS = "/api/v1/applications"
DOCUMENTS = "/api/v1/documents"
STUDENTS = "/api/v1/students"
PDF = b"%PDF-1.7\n1 0 obj\n<< /Type /Catalog >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF\n"
PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 64
DETAILS = {
    "date_of_birth": "2006-03-14",
    "highest_qualification": "12th PCM, 72%",
    "address": "Flat 4, Sea View Society",
    "city": "Mumbai",
    "state": "Maharashtra",
    "postal_code": "400001",
    "indos_number": "15ZL1234",
}


def use_memory_storage(h: Harness) -> InMemoryObjectStorage:
    storage = InMemoryObjectStorage()
    h.app.state.storage = storage
    return storage


async def active_course(h: Harness, csrf: str, prefix: str = "C") -> dict[str, Any]:
    return await new_course(h, csrf, f"{prefix}{uuid.uuid7().hex[-6:]}".upper())


async def new_application(
    h: Harness,
    csrf: str,
    *,
    course: dict[str, Any],
    campus: uuid.UUID,
    lead: dict[str, Any] | None = None,
    status: int = 201,
    **fields: Any,
) -> Any:
    body: dict[str, Any] = {"course_id": course["id"], "campus_id": str(campus), **fields}
    if lead is not None:
        body["lead_id"] = lead["id"]
    elif "full_name" not in fields:
        body.update(full_name="Meera Pillai", mobile=fake_mobile())
    response = await send(h, "POST", APPLICATIONS, csrf, body)
    return data(response, status) if status < 400 else response


async def patch(h: Harness, csrf: str, application: dict[str, Any], **changes: Any) -> Any:
    body = {**changes, "version": application["version"]}
    return await send(h, "PATCH", f"{APPLICATIONS}/{application['id']}", csrf, body)


async def ready(h: Harness, csrf: str, application: dict[str, Any]) -> dict[str, Any]:
    """Complete the details and the declaration."""
    return data(await patch(h, csrf, application, **DETAILS, declaration_confirmed=True))  # type: ignore[no-any-return]


async def submit(h: Harness, csrf: str, application: dict[str, Any]) -> Any:
    return await send(
        h,
        "POST",
        f"{APPLICATIONS}/{application['id']}/submit",
        csrf,
        {"version": application["version"]},
    )


async def review(
    h: Harness, csrf: str, application: dict[str, Any], to: str, reason: str | None = None
) -> Any:
    body: dict[str, Any] = {"to_status": to, "version": application["version"]}
    if reason is not None:
        body["reason"] = reason
    return await send(h, "POST", f"{APPLICATIONS}/{application['id']}/review", csrf, body)


async def admit(
    h: Harness,
    csrf: str,
    application: dict[str, Any],
    student: str = "new",
    student_id: str | None = None,
) -> Any:
    body: dict[str, Any] = {"student": student, "version": application["version"]}
    if student_id is not None:
        body["student_id"] = student_id
    return await send(h, "POST", f"{APPLICATIONS}/{application['id']}/admit", csrf, body)


async def upload(
    h: Harness,
    csrf: str,
    application_id: str,
    *,
    document_type: str = "PASSPORT",
    content: bytes = PDF,
    file_name: str = "passport.pdf",
    content_type: str = "application/pdf",
    replaces: str | None = None,
) -> Any:
    form: dict[str, str] = {"document_type": document_type}
    if replaces is not None:
        form["replaces_document_id"] = replaces
    return await h.client.post(
        f"{APPLICATIONS}/{application_id}/documents",
        data=form,
        files={"file": (file_name, content, content_type)},
        headers={"X-CSRF-Token": csrf},
    )


async def decide(h: Harness, csrf: str, document: dict[str, Any], reason: str | None = None) -> Any:
    if reason is None:
        return await send(
            h,
            "POST",
            f"{DOCUMENTS}/{document['id']}/verify",
            csrf,
            {"version": document["version"]},
        )
    return await send(
        h,
        "POST",
        f"{DOCUMENTS}/{document['id']}/reject",
        csrf,
        {"reason": reason, "version": document["version"]},
    )


async def approved(
    h: Harness, csrf: str, *, course: dict[str, Any], campus: uuid.UUID, **fields: Any
) -> dict[str, Any]:
    """An application with details, submitted and approved (no documents)."""
    application = await ready(
        h, csrf, await new_application(h, csrf, course=course, campus=campus, **fields)
    )
    application = data(await submit(h, csrf, application))
    return data(await review(h, csrf, application, "APPROVED"))  # type: ignore[no-any-return]


async def reload(h: Harness, application: dict[str, Any]) -> dict[str, Any]:
    return data(await h.client.get(f"{APPLICATIONS}/{application['id']}"))  # type: ignore[no-any-return]


def errors(response: Any) -> set[tuple[str, str]]:
    assert response.status_code == 422, response.text
    return {(d["field"], d["code"]) for d in response.json()["error"]["details"]}
