import { render } from "@testing-library/react";

import { ThemeProvider } from "@/design-system/theme/ThemeProvider";

import type { ReactElement } from "react";

// Renders a full screen inside the theme runtime (T01-09A tests). `theme`
// sets the resolved theme on <html> the way the pre-paint script does, so
// screens can be checked in Light and Dark (contrast itself is verified on
// the token layer and in Chromium; jsdom computes no colours).
export function renderScreen(
  screenElement: ReactElement,
  { theme = "light" }: { theme?: "light" | "dark" } = {},
) {
  document.documentElement.dataset.theme = theme;
  return render(<ThemeProvider>{screenElement}</ThemeProvider>);
}

/** Removes ids generated by React (useId) so two renders can be compared. */
export function normalizedHtml(element: Element): string {
  return element.innerHTML.replace(/_r_[0-9a-z]+_|:r[0-9a-z]+:/g, "ID");
}
