"""Declarative base, naming convention and shared column mixins (T01-01).

Conventions (docs/architecture/tenancy.md §9, backend-foundation.md §3):

* Every model inherits :class:`Base` and one or more mixins below.
* Primary keys: application-generated UUIDv7 (:class:`UUIDPrimaryKeyMixin`).
* Timestamps: ``timestamptz`` in UTC, set by the database
  (:class:`TimestampMixin`).
* Optimistic locking for concurrently edited aggregates
  (:class:`VersionedMixin`); a stale write raises ``StaleDataError``, which the
  API maps to ``409 CONFLICT``.
* Relationships must declare ``lazy="raise"`` (ADR-0001) so that nothing is
  loaded implicitly in async code; a test enforces this for every mapper.
* Constraint and index names are deterministic (:data:`NAMING_CONVENTION`),
  so Alembic migrations are reviewable and reversible.

Tenant, campus, actor and soft-delete mixins are added by the tasks that first
need them (T01-03 onwards), not here.
"""

import uuid
from datetime import datetime
from typing import Any, ClassVar

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

from app.core.ids import new_id

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every MTI 360 model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        datetime: DateTime(timezone=True),
    }


class UUIDPrimaryKeyMixin:
    """``id`` primary key: UUIDv7 generated by the application."""

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=new_id, sort_order=-10)


class TimestampMixin:
    """``created_at`` / ``updated_at`` maintained by the database (UTC)."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, sort_order=90
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        sort_order=91,
    )


class VersionedMixin:
    """Optimistic locking: ``version`` increments on every update.

    Concurrent writers that loaded the same version cannot both succeed: the
    second update matches no row and SQLAlchemy raises ``StaleDataError``.
    """

    version: Mapped[int] = mapped_column(nullable=False, default=1, sort_order=92)

    @declared_attr.directive
    def __mapper_args__(cls) -> dict[str, Any]:  # noqa: N805 - SQLAlchemy passes the class
        return {"version_id_col": cls.__table__.c.version}  # type: ignore[attr-defined]
